`
MIT License

Copyright (c) 2024 Neurs

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
`

const aDictContains366DaysThroughOutTheYearOnWhatAFloridaManAndWomanDidOnTheRequestedDay = {
    "0101":"Florida Man Shooting At Target In Backyard Hits Neighbor Sitting At Dining Room Table (WFLA)",
    "0201":"Florida Man Arrested For Attacking McDonald’s Employee Over Not Getting A Straw (ABC Action News)",
    "0301":"Florida Man Arrested At Mar-A-Lago, Says He Came To Talk To Trump About ‘His $6.3 Trillion’ (Local 10)",
    "0401":"Florida Man Finds His Lost Kitty 2,000 Miles Away In Colorado (Star Advertiser)",
    "0501":"Florida Man Puts Dragon Lizard In His Mouth, Smacks People With It (NY Daily News)",
    "0601":"Florida Man Intentionally Drove Ferrari 360 Into Ocean At Top Speed (Inquuisitr)",
    "0701":"Florida Man Says Multiple Syringes Found In Rectum Aren’t His (The Smoking Gun)",
    "0801":"Florida Man Arrested After Argument Over Cheesesteak (Local 10)",
    "0901":"Florida Man Accused Of Burning Son To Teach Him Lesson About Fire (WTSP)",
    "1001":"Florida Man Allegedly Fooled Family Into Believing Murdered Wife Was Still Alive (Rolling Stone)",
    "1101":"Florida Man Chews Up Police Car Seat After Cocaine Arrest (Florida Keys Sherrif Office)",
    "1201":"Florida Driver Finds Boa Constrictor In His Car Engine (WFLA)",
    "1301":"Drunk, Shirtless Florida Man Offer Parenting Advice At Park (NBC 2)",
    "1401":"Florida Man Threatens To Kill Man With ‘Kindness,’ Uses Machete Named ‘Kindness’ (Local 10)",
    "1501":"Florida Man Causes Highway Crash, Steals Good Samaritan’s Truck Who Stopped To help (CBS Local)",
    "1601":"Florida Man Who Drove Ferrari Into Water Said ‘Jesus Told Him To’ (Fox 43)",
    "1701":"Florida Man Chased Down By Horses While Eluding Cops (Click Orlando)",
    "1801":"Florida Man Bites Off Girlfriend’s Thumb During Argument (WTXL)",
    "1901":"Florida Man Tries To Order Burrito At Bank Drive-Through, Thinks It’s Taco Bell (Alt Press)",
    "2001":"Florida Man Caught ‘Stealing 850 Pairs Of Underwear From Victoria’s Secret’ (Daily Mail)",
    "2101":"Florida Man, Woman Run Over By Patrol Car While Lying In Road To Watch Eclipse (My Sun Coast)",
    "2201":"Florida Man Jumps Off Roof Onto Homeowner, Knocks Television Over, Empties Vacuum Cleaner, Masturbates (Gawker)",
    "2301":"North Florida Man Beat, Pepper Sprayed Mom Because ‘She Was A Narcissist’ (NBC Miami)",
    "2401":"Florida Woman’s Work As Phone Sex Operator Triggers Domestic Disturbance Call (The Smoking Gun)",
    "2501":"Naked Florida Man Runs Through Dunkin’ Donuts (Patch)",
    "2601":"Florida Man Finds A WWII Grenade, Places It In His Truck, Drives To Taco Bell (Triliist)",
    "2701":"Florida Man Steals $4,000 Worth Of Chicken And Ribs From Restaurant (Eater)",
    "2801":"Florida Man Finds World War Ii Hand Grenade, Brings It With Him To A Taco Bell (WMC Action News)",
    "2901":"Florida Man Thought He Was Stealing Opioids But Instead Got Laxatives, Police Say (USA Today)",
    "3001":"Florida Man Spent Weeks In Jail For Heroin That Was Actually Detergent (WFLA)",
    "3101":"Florida Man Allegedly Dug Tunnel To Rob Bank (Palm Beach Daily)",
    "0102":"Florida Man Steals $33k Of Rare Coins And Cashes In At Coinstar For $29.30 (Palm Beach Post)",
    "0202":"Stabbed In The Back At Gainesville Bar Over Remark On A Hat (Gainesville News)",
    "0302":"Florida Man Who Had Sex With Dolphin Says It Seduced Him (Deccan Chronicle)",
    "0402":"Police Arrest Florida Man For Drunken Joyride On Motorized Scooter At Walmart (The Smoking Gun)",
    "0502":"Florida Men Accused Of Smearing Feces On Crunch Fitness Bathroom, Sauna (WFTV)",
    "0602":"Florida Man Tries To Run Over Son Who Wouldn’t Take Bath (KCBD)",
    "0702":"Florida Man Dances Through DUI Sobriety Test (Local 10)",
    "0802":"Florida Woman Poses For Maternity Photos With Baby Gator (WCTV)",
    "0902":"Fries With That? Florida Man Accused Of Tossing Gator At Drive-Through (Tampa Bay)",
    "1002":"Florida Man Believes Wrestling Event Is Haunted By The Ghost Of Macho Man Randy Savage (UP Roxx)",
    "1102":"Wheelchair-Bound Florida Woman, 74, Ran Heroin Sales For Florida Drug Gang (The Smoking Gun)",
    "1202":"Florida Woman Assaults Husband After Finding Dildo Among His Belongings (The Smoking Gun)",
    "1302":"Florida Couple Arrested For Having Sex On Sidewalk In Broad Daylight … Again (The Smoking Gun)",
    "1402":"Florida Man Caught On Camera Licking Doorbell (WFLX)",
    "1502":"Florida Man Believes Ghost Of Macho Man Randy Savage Is Haunting Local Wrestling Promotion (UP Roxx)",
    "1602":"Noisy Sex Triggers Brawl Between Florida Brothers Who Still Live With Their Mom (The Smoking Gun)",
    "1702":"Cops Bust Man For Brazen Theft Of $6500 Rolex From Florida Airport TSA Screening Checkpoint (The Smoking Gun)",
    "1802":"Florida Man Claims To Be ‘Agent Of God,’ Carries Rattlesnake On Beach (ABC 7)",
    "1902":"Florida Man Arrested For Trafficking Cocaine-Stuffed Lunchables In Ford F-150 (The Drive)",
    "2002":"Florida Man Loses Wallet In Hooters, Blames Tots For Distracting Him (The Smoking Gun)",
    "2102":"Florida Man Charged With Throwing Toilet At East St. Louis Board Of Education (Fox 2 Now)",
    "2202":"Florida Man Throws Toilet Through School Board Building Window In Illinois, Is Arrested Sitting On Another (Newsweek)",
    "2302":"Man Lists ‘Redneck’ As Religion On Florida Police Report (The Smoking Gun)",
    "2402":"Florida Couple Arrested After Having Sex In Rear Of Police Squad Car (The Smoking Gun)",
    "2502":"Florida Man Vaped His Friend’s Ejaculate (Gawker)",
    "2602":"Florida Man Assaulted Teen Relative With Taco Bell Burrito (The Smoking Gun)",
    "2702":"Florida Man For Soliciting Undercover Cop To Smell Her For Money (The Smoking Gun)",
    "2802":"Florida Man Who Allegedly Threatened Family With Coldplay Lyrics Ends Standoff After SWAT Promises Him Pizza (MSN)",
    "2902":"Florida Man Leaves Anal Plug In Cop Car During DUI Arrest (Huffington Post)",
    "0103":"Florida Man Accused Of Masturbating In Front Of Children Says He Was Adjusting Hernia (WRIC)",
    "0203":"Florida Man Captured On Surveillance Video Flaunting Stolen Car Keys At Lot (KTLA)",
    "0303":"Florida Man Goes On LSD-Fueled Naked Rampage, Bites Girlfriend’s Finger (Palm Beach Post)",
    "0403":"Florida Man Arrested After Fight About Tupac Shakur (Miami Herald)",
    "0503":"Leaf-Burning Florida Man Asks Cop ‘Did You Find All My Pot?’ (Miami Herald)",
    "0603":"Florida Man Tries To Board Flight While Carrying Fake Grenade (Orlando Weekly)",
    "0703":"Florida Family Hospitalized After Eating LSD-Laced Steak Bought At Walmart (The Smoking Gun)",
    "0803":"Florida Woman Crashes Car While Shaving Bikini Area (NY Post)",
    "0903":"Florida Lawyer’s Pants Catch On Fire In Court (ABC Action News)",
    "1003":"Florida Man Who Attacked McDonald’s Worker Over Straw Sentenced To Jail (Fox News)",
    "1103":"Florida Man’s Church Loses Tax-Exempt Status Because It’s Just A Nightclub (Vice)",
    "1203":"Florida Man Found Bound, Gagged, Dressed In Women’s Clothes And Left In Abandoned Building (The Smoking Gun)",
    "1303":"Florida Woman Threatens Hair Salon With Machete, Poops In Patrol Car (WCTV)",
    "1403":"Florida Keys Man Busted For Theft Of Couple’s “Bag Of Dildos” (The Smoking Gun)",
    "1503":"Florida Man Steals Cable Truck, Knocks Out Service For Thousands (Brevard Times)",
    "1603":"Florida Newlywed Squabble Involved G-String, Dancing, Making Mess While Cooking Dinner (The Smoking Gun)",
    "1703":"Florida Woman Arrested For Biting Spouse During Sex (The Smoking Gun)",
    "1803":"Florida Woman Sets Car On Fire After Man Refuses To Buy McFlurry (CNS News)",
    "1903":"“Obnoxious” Shirtless Florida Karaoke Singer Allegedly Assaults Applebee’s Employee (The Smoking Gun)",
    "2003":"Florida Man Tries To Sell 3 Iguanas Taped To His Bike To Passersby As Dinner (NY Daily News)",
    "2103":"Florida Men, One Dressed In Bull Onesie, Attempt To Burn Down House With Ragu Sauce (Fox News)",
    "2203":"Florida Man Calls Police To Complain He Was Ripped Off After Paying For Sex (Miami Herald)",
    "2303":"Florida Man Drinks $80 Worth Of Jägermeister Shots, Sets Fire To Bar (NY Daily News)",
    "2403":"Florida Man Steals Hot Air Balloon From Indiana During Florida Man Challenge (Brevard Times)",
    "2503":"Florida Man Steals From Walmart, Uses Shopping Cart As Getaway Car (Brevard Times)",
    "2603":"Florida Woman Kept Calling 911 To Report Boyfriend Was “Not Being Nice To Her” (The Smoking Gun)",
    "2703":"Florida Man Arrested For Stealing Vibrator For Girlfriend From Spencer’s Gifts (The Smoking Gun)",
    "2803":"Pensacola Woman Mistakes 37-Week Pregnancy For Bad Chinese Food (PNJ)",
    "2903":"Florida Man Drives Six Miles With Wife Atop Car (The Smoking Gun)",
    "3003":"Florida Man Urinates On Table, Exposes Self In Church (Daily Commercial)",
    "3103":"Florida Woman Calls 911 Because Her Bacon Pizza Had Hamburger Instead (Inquisitr)",
    "0104":"Florida Woman Arrested For Fondling Breasts And Nipple Rings In Cafe (The Smoking Gun)",
    "0204":"Florida Man Threatened To Stab Dinner Host Over Easter Ham Consumption (The Smoking Gun)",
    "0304":"Florida Man Can’t Get Car He Wants To Steal To Start (Miami Herald)",
    "0404":"Florida Man Had Handcuff Key In His Butt During High Speed Chase (Action News)",
    "0504":"Florida Man Tries To Buy $60,000 BMW With Food Stamps (Zero Hedge)",
    "0604":"Florida Man Helps Amputee Up Stairs, Then Returns To Build Ramp (6 ABC)",
    "0704":"Florida Man Tries To Escape Cops On His Hoverboard, Fails (The Smoking Gun)",
    "0804":"Florida Man Arrested For Serial Gropings On YouTube: “If You Don’t Touch Ass You’re Crazy” (Miami News Times)",
    "0904":"Days After Buying $8 Million Private Island, Florida Man Busted For Stealing $300 In Merch From Kmart (The Smoking Gun)",
    "1004":"Florida Man Tries To Kiss Cottonmouth Snake (Outdoor Hub)",
    "1104":"Florida Man Had Daughter Sell Pot Brownies At School (Brevard Times)",
    "1204":"Florida Man Is Busted With $100k Worth Of Stolen Goods, Hides Drugs Up Butt (Daily Mail)",
    "1304":"Florida Man Impersonating A Police Officer Pulls Over Real Cops (NBC 2)",
    "1404":"Florida Man Humps Stop Sign While Stalking Ex (ABC Action News)",
    "1504":"Florida Man Lands Gyrocopter On Capitol Lawn To Demand Campaign Finance Reform, Is Arrested (Washington Post)",
    "1604":"Florida Man Asks Cashier About Stealing Beer, Then Does It Anyway And Gets Arrested (Tampa Bay)",
    "1704":"Police Arrest Florida Woman, 22, For Violently Yanking Penis Of Ex-Boyfriend (The Smoking Gun)",
    "1804":"Florida Man Celebrates Earth Day With Sand Art, Leaves Death Traps For Sea Turtles (Brevard Times)",
    "1904":"Half-Nude Florida Man Wearing Underwear Marked “Breathalyzer, Blow Here” Arrested For DUI (The Drive)",
    "2004":"Fight Over Facebook Post Causes Florida Woman To Lose Toe (AJC)",
    "2104":"Florida Man Impersonated Cop, Used Sirens To Rush Through Traffic (WFLA)",
    "2204":"Florida Man Tries To Kiss Cottonmouth Snake (ABC News Go)",
    "2304":"Florida Man Defends Small Chihuahua With Large Machete (Orlando Sentinel)",
    "2404":"Florida Woman Asks Police For Help Getting Refund From Her Drug Dealer (The Smoking Gun)",
    "2504":"Identical Twin Florida Men Arrested After Getting In Brick Fight (NY Daily News)",
    "2604":"Rowdy Florida Woman Explains To Cops, “You Can’t Tell Me What To Do. Obama Owns This Motherfucker!” (The Smoking Gun)",
    "2704":"Police: Florida Man Confronts Officers With Viking-Style Ax (Palm Beach Post)",
    "2804":"Florida Man Arrested For Grand Theft After Trying To Walk Out Of Store With AK-47s Stuffed Down His Pants (NBC Miami)",
    "2904":"April 29 Florida Woman Offers Favors For $25 And Chicken McNuggets (Brevard Times)",
    "3004":"Florida Man Eats Crack Cocaine; Tells Police It’s Jolly Rancher Candy (107.9 WNCT)",
    "0105":"Florida Man Wearing “Jail Sucks!” T-Shirt Is Booked Into Jail For Welfare Fraud (The Smoking Gun)",
    "0205":"Florida Man Tries To Swim Away From Police After Exposing Himself (Viral News)",
    "0305":"Florida Man Tells Police That His Name Is Fuck You’ (Palm Beach Post)",
    "0405":"Florida Woman Arrested For Threatening To Kill Neighbor Says She Should Have Threatened To ‘Bitch Slap’ Him (The Smoking Gun)",
    "0505":"Florida Lawyer Disbarred For Sleeping With Her Clients (Brevard Times)",
    "0605":"Florida Woman Pulls Alligator From Her Yoga Pants During Traffic Stop (Fox News)",
    "0705":"Florida Woman’s Gruesome Roach-In-Ear Tale Goes Viral (NBC Miami)",
    "0805":"Florida Man Arrested For Refusing To Remove ‘I Eat Ass’ Sticker From Car Window (Fox News)",
    "0905":"Florida Man Fleeing From Police Is Attacked By Alligator (The Smoking Gun)",
    "1005":"Florida Woman Stabbed Boyfriend After He “Farted In Her Face” (The Smoking Gun)",
    "1105":"Florida Wanna Be Rapper Robs Store With BB Gun (The Smoking Gun)",
    "1205":"Florida Man Pulled Over With Alligator Foot In Dashboard (NY Daily)",
    "1305":"Florida Doom Metal Fan Turns Himself In After “Murdering His Imaginary Friend” (Metal Injection)",
    "1405":"Florida Man Celebrates Wedding By Getting Arrested For Soliciting Hooker On His Honeymoon (The Smoking Gun)",
    "1505":"Florida Man Runs From Deputies In General Lee Replica (WTSP)",
    "1605":"Florida Man Calls 911 On Himself (Floriduh Today)",
    "1705":"Florida Woman Tells Cops She Was “Too Lazy” To Pay For Sex Toys Stolen From Walmart (The Smoking Gun)",
    "1805":"Tattooed Florida Man Wearing Underwear And Hot Pink Bra Arrested For Erratic Driving And False License Plates (The Smoking Gun)",
    "1905":"Florida Man Arrested After Falling Asleep During Home Burglary (Brevard Times)",
    "2005":"Florida Man Allegedly Threatened To Behead Cops, Eat Their Eyes (NY Post)",
    "2105":"Florida Man Climbs Atop Playground Equipment At Clearwater Park, Tells Kids Where Babies Come From (Tampa Bay News)",
    "2205":"Florida Man Points Loaded Shotgun At Irs Worker Who Knocked At His Door (Sun Sentinel)",
    "2305":"Florida Man Burglar Tries To Make Getaway In A Golf Cart, Lands In A Pond (Miami Herald)",
    "2405":"Florida Man Takes Sledgehammer To Game At St. Petersburg Convenience Store (Tampa Bay News)",
    "2505":"Florida Man Climbs Through Drive-Thru Window To Steal Cash Register (News 4 Jax)",
    "2605":"Florida Man Accidentally Shoots, Kills Woman During Foreplay (ABC Action News)",
    "2705":"Key West Looking For Owner Of Illegally Parked Flintstones Car (Local 10)",
    "2805":"Florida Man Attacks Mom With Corn On The Cob (WWLP)",
    "2905":"82-Year-Old Florida Man Slashes 88-Year-Old Florida Woman’s Tires With An Ice Pick For Taking His Seat At Bingo (Globe and Mail)",
    "3005":"Florida Man Tries To Smuggle McDonald’s Burgers, Sandwiches, Chewing Tobacco Into Jail (Action News)",
    "3105":"Florida Man Arrested, Tells Cop His Name Is “Ben Dover” (The Smoking Gun)",
    "0106":"Florida Man Stabs Roommate Over Groceries (Florida Today)",
    "0206":"Florida Man Flashing Cash On Facebook Live Interrupted By Police Raid (AJC)",
    "0306":"Florida Man Who Threw Alligator Into Wendy’s Drive-Thru Window Sentenced (Fine Notes)",
    "0406":"Florida Man Pours Salt On Floor Of Walmart To Get Rid Of “Evil Spirits” Around Him (CBS 12)",
    "0506":"Florida Woman ‘plays Mermaid’ And Entered Homes Without Permission (WMAZ 13)",
    "0606":"Florida Man Tries To Break Into ATM With Blowtorch, Welds It Shut Instead (My News 13)",
    "0706":"Florida Man Arrested For Alleged Kale Heist At Walmart (The Smoking Gun)",
    "0806":"Florida Man Calls 911 After Girlfriend Refuses To Buy Him Vodka (NBC 2)",
    "0906":"Florida Man Polk Uses Marijuana Plants To Beat Brother (WESH)",
    "1006":"Florida Man Accused Of Masturbating, Exposing Self To Woman: ‘It’s A Nice View’ (Local 10)",
    "1106":"Man Smacks Wife “Upside The Head” After She Uses Lord’s Name In Vain During Argument (The Smoking Gun)",
    "1206":"Florida Man Plays Naked Game Of ‘Ding Dong Ditch’ (Palm Beach Post)",
    "1306":"Florida Man Says He Steals Pool Floats For Sex Instead Of Raping Women (Brevard Times)",
    "1406":"Florida Man Accused Of Taking 4-Year-Old On Burglary Spree (CBS Local)",
    "1506":"Florida Man Chugged Can Of Beer During DUI Stop (AP News)",
    "1606":"Florida Man Wakes Up Naked In Stranger’s Home (Palm Beach Post)",
    "1706":"Florida Man Found With Mobile Meth Lab In Walmart Parking Lot (Palm Beach Post)",
    "1806":"Florida Man Looking To Buy Tamarac Home Buys 100-Square-Foot Strip Of Land Instead (WSVN)",
    "1906":"Florida Man Offers Decent Rationale For Stealing Trojan Twister Vibrator From Walgreens (The Smoking Gun)",
    "2006":"Florida Man Couldn’t Drive Stick Shift During Carjacking (Brevard Times)",
    "2106":"Florida Woman Shoots Naked, Poop-Covered Intruder (WPTV)",
    "2206":"Florida Man Steals Clothes, Bites Security Guard, Flees In Gold Convertible (Naples News)",
    "2306":"Florida Contractor Fakes Death To Dodge Angry Homeowners (Tampa Bay News)",
    "2406":"Teen Killed Grandmother, Drove Body Around Nudist Community (WFTV)",
    "2506":"Florida Man Steals Dump Truck — Shoots At Helicopter In Pursuit (Fox 13)",
    "2606":"Florida Good Samaritan Helps Reunite A Child With Her Parents, Gets Beat Up By Her Dad (ABC Action News)",
    "2706":"McDonald’s Employee Assaulted In Florida Over Broken Ice Cream Machine (ABC Action News)",
    "2806":"Florida Man Gets 10 Days In Jail For Punching Swan (24 News)",
    "2906":"Florida Man Steals Van So He Can Drive To Waffle House (Democratic Underground)",
    "3006":"Florida Man Claims He Invented iPhone In 1992, Sues Apple For $10 Billion (Game Spot)",
    "0107":"Florida Man Accused Of Using Makeshift Flamethrower To Threaten Woman (Palm Beach Post)",
    "0207":"Florida Man Unaware He’s Not Allowed To Shoot At Strip Club From His Vehicle (Off the Beat)",
    "0307":"Florida Man Appears To Have Sex With Tree In View Of Passing Drivers (WY Daily)",
    "0407":"Florida Man Blows Fingers Off The Day Before Fourth Of July (WTF Florida)",
    "0507":"Florida Man Tells Cop He “Really Enjoyed” Resisting Arrest Because It Was Like Being On A TV Show (The Smoking Gun)",
    "0607":"Florida Woman Goes To Car Dealership, Pretends To Be Manager, Fires Employees (WGNO)",
    "0707":"Florida Woman Accused Of Murdering Her Father, Living With The Body For Several Days (ABC 6)",
    "0807":"Florida Man Tells Cops “just A Small Time Drug Dealer Trying To Make A Dollar” (The Smoking Gun)",
    "0907":"Florida Man With No Pants Is Arrested After A Pursuit (Busted Locals)",
    "1007":"Florida Man Wasn’t Drinking While Driving, Just At Stop Signs (PNJ)",
    "1107":"Florida Man Escapes Alligator By Punching It In The Face While Searching For Golf Balls (USA Today)",
    "1207":"Police: Florida Man Forgets To Untie Boat While Stealing It (Palm Beach Post)",
    "1307":"Florida Man Steals Operating Table From Hospital (The Smoking Gun)",
    "1407":"Florida Man Steals $2 Million In Legos (Chicago Tribune)",
    "1507":"Florida Man Robs Bank, Covers Himself In Feces To Try To Escape Custody (Palm Beach Post)",
    "1607":"Florida Man Indicted in Fatal Dog Poop Fight (CBS News)",
    "1707":"Florida Man’s Murder Was Really Elaborate Suicide By Balloon (Fox 59)",
    "1807":"Florida Man Uses Electric Guitar In Failed Robbery (Sun Sentinel)",
    "1907":"Florida Man Shoots At ‘Pokemon Go’ Players Outside House (Charlotte Observer)",
    "2007":"Florida Man Says He Went ‘Bananas,’ Shot Out Utility Workers’ Tires (CBS Local)",
    "2107":"Florida Man Livestreams His Police Chase As He Runs Over Beach Chairs And Swigs Whiskey (Miami Herald)",
    "2207":"Florida Man Fakes Identity For 20 Years, Duped Wife (WREG)",
    "2307":"Naked Florida Man Throws Large Objects Into Traffic From 30-Story Building (ABC Action News)",
    "2407":"Brave Florida Man Serves Up Hot Dog Lunch For Alligators Straight From His Mouth (ABC 13)",
    "2507":"Florida Man Bites Neighbor’s Ear Off Over A Cigarette (Top Viral)",
    "2607":"Florida Church Organist Busted In Glory Hole Gambit (The Smoking Gun)",
    "2707":"Florida Man Throws Salsa Jar At Car In Road Rage Attack (Orlando Sentinel)",
    "2807":"Florida Man Makes Beer Run With Gator In Hand (Fox 6)",
    "2907":"Florida Man Says Cops Mistook Krispy Kreme Doughnut Glaze For Meth And Arrested Him (Complex)",
    "3007":"Florida Man Assaults Sister Because She Got His Dinner At McDonald’s, Not Chinese Takeout Joint (The Smoking Gun)",
    "3107":"Florida Man Hit By Car During Failed ‘In My Feelings’ Challenge (Denver Channel)",
    "0108":"Florida Man’s Boat Burns After Using The Bathroom (Palm Beach Post)",
    "0208":"Florida Man Charged With Picking Magic Mushrooms While Carrying An Alligator (Brevard Times)",
    "0308":"Florida Man Attacks Flamingo At Busch Gardens (Brevard Times)",
    "0408":"Florida Man Opens Fire At “Peace In The City” Back To School Giveaway (Florida Today)",
    "0508":"Florida Mom Busted For Biting Teen Daughter’s Breast During Bloody Domestic Battle (The Smoking Gun)",
    "0608":"Drunk Florida Man Goes On Beer Run With Gator (WTF Florida)",
    "0708":"Accused Florida Man Says His Cat Downloaded Child Porn, Not Him. (NBC Miami)",
    "0808":"Florida Man Sick Of His $1000000 Island, Wants To Trade For A Porsche 918 (Jalopnik)",
    "0908":"Florida Man Attacks Person Over Parking Space (Palm Beach Post)",
    "1008":"Florida Man Arrested With ‘Fuck The Police’ Face Tattoo (The Smoking Gun)",
    "1108":"Florida Man’s Robbery Foiled By Angry Birds Backpack (Brevard Times)",
    "1208":"Florida Man Banned From Ordering Pizza After Harassing Restaurants (TC Palm)",
    "1308":"Judge Unamused At Florida Man’s Twerking Ability (TJC News)",
    "1408":"Florida Woman Motorist Tried To Frame Her Own Dog In Hit-And-Run Accident, Told Cops To Arrest Pooch (The Smoking Gun)",
    "1508":"Florida Man Wrecks Liquor Shop, Blames Caterpillar From Alice In Wonderland (ABC Action News)",
    "1608":"Florida Man Claiming To Be Pastor Charged With Fraud (Local 10)",
    "1708":"Florida Man Breaks Into Home, Steals Sausages (Florida Today)",
    "1808":"Florida Man Throws Tight Spiral Right Into Kid’s Face (Politico)",
    "1908":"Florida Teens Arrested For Defecating In Pool (The Smoking Gun)",
    "2008":"Cops Arrest Florida Man, 40, For Sauerkraut Battery On Girlfriend (The Smoking Gun)",
    "2108":"Florida Man Found Naked In Tree (News Talk Florida)",
    "2208":"Florida Man Threatens To Feed Children To Alligators (Palm Beach Post)",
    "2308":"Police: Florida Man Lines Garage With More Than $100k In Stolen Amazon Orders (Palm Beach Post)",
    "2408":"Florida Woman Busted For DUI Tells Cop, “This Is What I Get For Being A Bridesmaid” (The Smoking Gun)",
    "2508":"Florida Woman Arrested After Vandalizing And Setting Ex-Husband’s House On Fire (Tampa Bay)",
    "2608":"Florida Man Arrested Following Unprovoked Potato Salad Attack On His Mother (The Smoking Gun)",
    "2708":"Florida Woman Assaults Man Who Declined Her Offer Of Sex (The Smoking Gun)",
    "2808":"Florida Stripper Hangs Up On Cop Trying To Find Her Missing Child Saying “I Have To Get On Stage” (The Smoking Gun)",
    "2908":"Florida Man Caught Eating Meth Soaked Drawings Smuggled In Jail (News Herald)",
    "3008":"Florida Man Named Vladimir Putin Arrested For Screaming In Publix (CBS 12)",
    "3108":"Florida Man Reached Into Drive-Thru Window And Groped Taco Bell Worker (The Smoking Gun)",
    "0109":"Florida Man Videotaped Catching Gator With Bare Hands Faces Felony Charges (CBS 12)",
    "0209":"27th Arrest For Bikini-Clad Florida Man (Opposing Views)",
    "0309":"Florida Man Caught Burgling Home; Offers Homeowner Lawn Services If He Doesn’t Call The Cops",
    "0409":"Florida Man Shoots Up Home Over Bad Restaurant Review On Social Media (Click on Detroit)",
    "0509":"Florida Man Caught With 200 Illegal Lobsters (CBS Local)",
    "0609":"Florida Man Uses His Own Wanted Poster As Facebook Profile Picture (ABC News)",
    "0709":"Florida Man, Drunk And Naked, Allegedly Set House On Fire In Failed Cookie Baking Attempt (PNJ)",
    "0809":"Florida Man Steals Patrol Car, Asks ‘This Is A Felony?’ (Palm Beach Post)",
    "0909":"Shirtless Florida Man Punches At Cars After Disrupting Bar Show (Palm Beach Post)",
    "1009":"Naked Florida Man Causes Fire While Baking Cookies On George Foreman Grill (Local 10)",
    "1109":"Florida Man Sings ‘Don’t Stop Believin’ In Cop Car While On Journey To Jail (Tampa Bay)",
    "1209":"Florida Man Asks Cousin To Test Flak Jacket With Real Gunfire, Cousin Ends Up With Manslaughter Charge (Washington Post)",
    "1309":"Florida Man” Ends Argument With Chainsaw (Big Heart Radio)",
    "1409":"Shirtless Florida Man Travels To Myrtle Beach To Head Bang During Hurricane Florence (Orlando Weekly)",
    "1509":"Florida Man Says Slurred Speech Is Because Of Wisdom Teeth, Not Booze (Palm Beach Post)",
    "1609":"Florida Man Arrested After Sniffing Feet Of Library Patrons (CBS News)",
    "1709":"Bicycling Florida Man Shot During Tattoo Argument (WTF Florida)",
    "1809":"Florida Man, 54, Jailed For Trying To Forcibly Exorcise Devil Out Of His 80-Year-Old Girlfriend (The Smoking Gun)",
    "1909":"Neighbors Complain About Florida Man Doing Yard Work Naked, Police Say It Is Legal (WEAR TV)",
    "2009":"Florida Mom Takes Pics On Baby In Trash Can, Under Mattress To Torment Father (The Smoking Gun)",
    "2109":"Florida Man Arrested For Trying To Bring Unregistered Glock Through Airport TSA Checkpoint (Flyer Today)",
    "2209":"Florida Mom Arrested For Cheering Child On In Fight (The Smoking Gun)",
    "2309":"Florida Man Left His Child In A Locked Car While Partying At A Strip Club (The Smoking Gun)",
    "2409":"Naked Florida Man Tries To Start Fight At Chick-Fil-A (WTXL)",
    "2509":"Florida Man Throws Bike And Its Owner Off Bridge (US News)",
    "2609":"Florida Man Arrested For Washing Cursing Girlfriend’s Mouth Out With Dawn Liquid Dish Detergent (The Smoking Gun)",
    "2709":"Florida Man In Undies Hangs With Pot On Highway (TC Palm)",
    "2809":"Florida Man Arrested After His Surveillance Cameras Recorded Him Dealing Drugs (ABC Action News)",
    "2909":"Florida Grandma Tries Scaring Off Naked Florida Man By Pulling Her Dentures Out (WTF Florida)",
    "3009":"Florida Woman Who Rode Manatee Arrested (Fox News)",
    "0110":"Florida Woman Ends Up Behind Bars After Robbery (The Smoking Gun)",
    "0210":"Florida Man Drinks Goat Blood In Ritual Sacrifice, Runs For Senate (Talking Points)",
    "0310":"Florida Man, 74, Arrested For Battering Wife, 47, During Argument Over “Obama And Romney” (The Smoking Gun)",
    "0410":"Florida Man Running In Inflatable Bubble Rescued By Coast Guard (CNN)",
    "0510":"Florida Man Assaulted With Soda After Asking Fellow Moviegoer To Be Quiet (The Smoking Gun)",
    "0610":"Pocket-Dial To 911 Sinks Florida Trio Operating Meth Lab In Backyard Shed (The Smoking Gun)",
    "0710":"Florida Man Sets Fire To Another Homeless Man (News Tribune)",
    "0810":"Florida Man Sets Up Fake Office To Steal Peoples’ Identities And Urine (Palm Beach Post)",
    "0910":"Florida Brothers Kill Man To Steal His Rare Magic The Gathering Cards (Daily Mail)",
    "1010":"Drunk Florida Man Tries To Use Taco As Id After His Car Catches Fire At Taco Bell (Miami New Times)",
    "1110":"Florida Man Googled “How To Rob A Bank” Before Robbing A Bank (The Smoking Gun)",
    "1210":"Florida Woman, 23, Used Periscope To Live Broadcast Her Drunk Driving (The Smoking Gun)",
    "1310":"Florida Man Steals 36,000 Pounds Of Crisco (Tampa Bay News)",
    "1410":"Floridian, 19, Arrested For Lewd Act With Stuffed Animal Inside Walmart Store (The Smoking Gun)",
    "1510":"Florida Man Charged With Pleasuring Self On Amtrack, Claimed “Itchy Stomach” (Brevard Times)",
    "1610":"Florida Man Sets Self On Fire While Trying To Burn Cross (Brevard Times)",
    "1710":"Florida Couple Had Sex Atop Restaurant Table While Parents, Kids Watched (The Smoking Gun)",
    "1810":"Florida Mechanic Maintains White House Helicopters Arrested In Meth Bust (The Smoking Gun)",
    "1910":"Florida Man Accused Of Cutting Off Penis Of Ex-Girlfriend’s Boyfriend (KSLA)",
    "2010":"Florida Teacher Fired For Throwing X-Rated Party In Classroom (Palm Beach Post)",
    "2110":"Falling Palm Tree Kills Woman In Hammock In Florida (AP News)",
    "2210":"Florida Man Arrested For Throwing Pennies At Democratic Party Office (The Smoking Gun)",
    "2310":"Florida Man Allegedly Justifies Groping A Woman’s Breast During A Flight: Trump Says It’s ‘OK’ (Law and Crime)",
    "2410":"Florida Cop Pawns Guns He Was Loaned To Teach Concealed Weapons Class (WESH)",
    "2510":"Florida Man Ties Up 12 Foot Alligator To Tree In Local Neighborhood (Tampa Bay)",
    "2610":"Florida Man Steals Dollar Bills Stapled To Bar Wall, Tries To Spend Them At Publix (Herald Tribune)",
    "2710":"Mysterious Glory Hole Driller Strikes Again, Report Vexed Florida Police (The Smoking Gun)",
    "2810":"Florida Man Arrested For Stealing $500 In Wine (Florida Keys Sheriff Office)",
    "2910":"Florida Cops Roll Up On Dispute Call While Blasting ‘Why Can’t We Be Friends’ From Car Speakers (Jacksonville News)",
    "3010":"Florida Man, 21, Gets Mom Arrested After She Slaps Him In Face For Being Rude Freeloader (The Smoking Gun)",
    "3110":"Florida Woman, 25, Arrested For Ninja Star Attack On Her Younger Brother (The Smoking Gun)",
    "0111":"Florida Man Stands In Store Parking Lot Waving At Customers And Masturbating (News Herald)",
    "0211":"Tutu Wearing Florida Man Breaks Into Farmers Market (ABC Action News)",
    "0311":"Florida Woman Woman Arrested For DUI On A Horse, Charged With Animal Neglect (ABC Action News)",
    "0411":"Arrest Warrant Issued For Florida Man, 23, Charged In Humiliating Theft Of Life-Size Justin Bieber Cutout (The Smoking Gun)",
    "0511":"Florida Woman Claims She Was Handed Baby At Disney Resort (Sun Coast)",
    "0611":"Florida Man Accused Of Breaking Into Alligator Farm Is Attacked By Crocodile, Leaves Croc Shoe Behind (Inquisitr)",
    "0711":"Florida Man Stuffs Pizza, Cinnamon Sticks In Mouth Instead Of Paying (Palm Beach Post)",
    "0811":"Florida Man Claims Name Is ‘Ben Dover’ During Arrest Intake (The Smoking Gun)",
    "0911":"Florida Man Offers Chicken Dinner And $3 To Get Lucky (Brevard Times)",
    "1011":"Naked Florida Man Runs Into Woman’s Home, Tries On Her Clothes (WFLA)",
    "1111":"Florida Man Advertises Counterfeit Cash For Sale On Craigslist (Brevard Times)",
    "1211":"Florida Sheriff’s Office Web Site Falsely Claims Eminem Arrested With ‘200 Rocks’ Of Crack Cocaine (The Smoking Gun)",
    "1311":"Florida Man Gets In 8 Hour Standoff With Police, Says He Was Just Shooting Rats In His Backyard The Whole Time (ABC News Go)",
    "1411":"Florida Man Shoots Up Meth, Howls And Stomps On Roofs, Tells Cops He’s Waiting For DEA (AJC)",
    "1511":"Florida Man Calls 911 During Police Chase And Asks For Donald Trump (ABC Action News)",
    "1611":"Florida Man Steals Vending Machine (Miami Herald)",
    "1711":"Florida Surgeon Removes Healthy Kidney He Thought Was A Tumor (WATE)",
    "1811":"Florida Man Accidentally Shoots And Kills Woman During “Freaky Sex” (Complex)",
    "1911":"Accused Florida Butt Injector Appears To Have Tried Her Own Product (The Smoking Gun)",
    "2011":"Florida Man Catches Shark That Bit Him, Pledges To Eat It (Weather Plus)",
    "2111":"Cops Summoned To Florida Elementary School After Girl Kisses Boy In Phys Ed Class (The Smoking Gun)",
    "2211":"Florida Man Stabs Father For Trying To Circumcise Him (CBS News)",
    "2311":"Florida Man Denies Assaulting Girlfriend Over Her Use Of Large Sex Toy (The Smoking Gun)",
    "2411":"Florida Man Jacks Off In Pickup Truck Outside Walgreens (Sebastian Daily)",
    "2511":"Florida Man Takes A Leak In Sheriff’s Backyard (Palm Beach Post)",
    "2611":"Florida Man In Crocodile Pit Could Lose Foot, Blames Drugs For Incident (Dayton Daily News)",
    "2711":"Florida Man Accused Of Stabbing Woman Over Underdone Potato (CBS Local)",
    "2811":"“Fighting Is What Redneck People Do” Explained Drunk Florida Man Who Shot Lawnmower, Brawled With Teen Son (The Smoking Gun)",
    "2911":"Florida Man Orders Pizza, Stuffs It Into His Mouth Instead Of Paying (TC Palm)",
    "3011":"Florida Man Calls Himself Satan, Threatens To Kill If Not Given A Car (WTSP)",
    "0112":"Naked Florida Man Drives Around With Electrical Wires Wrapped Around Penis (Local 10)",
    "0212":"Florida Man Installs Giant Penis Mailbox (Fox 4 News)",
    "0312":"Florida Man Calls 911, Tells Cops: “Take Me To Jail, Motherfucker!” (Sebastian Daily)",
    "0412":"Florida Man Named ’Shaquille O’Neal’ Steals Veteran’s Wheelchair, Crashes Car (Palm Beach Post)",
    "0512":"Florida Man Leaving Strip Club Runs Himself Over With His Own Truck (Miami Herald)",
    "0612":"Florida Man Goes To Job Interview, Then Steals Shoes To Give To His Mom (ABC Action News)",
    "0712":"Florida Man Yells ‘there’s No Santa’ At Holiday Event (Spokesman)",
    "0812":"Florida Man Arrested After Driving 110 Mph While Naked With 3 Women In A Cadillac (Esquire)",
    "0912":"iPhone Recorded Florida Granny Shooting Her Son-In-Law (The Smoking Gun)",
    "1012":"Florida Man Growing Weed Hears Police Activity, Panics And Turns Himself In (Fox 59)",
    "1112":"Florida Man Shoves Footlong Sandwich Down His Pants (Newsweek)",
    "1212":"Florida Man Wearing Bucket On Head Breaks Into Pet Shop, Steals Pigeons (Palm Beach Post)",
    "1312":"Florida Man Find Credit Card On The Street, Uses It To Get Pedicure, Gets Arrested (The Smoking Gun)",
    "1412":"Wife Finds Strange Florida Woman Asleep In Husband’s Clothes (Brevard Times)",
    "1512":"Florida Man Steals Swan Boat, Gets Stranded On Lake Eola Fountain (Orlando Weekly)",
    "1612":"Florida Man Tases Cop With Own Taser (ABC 7)",
    "1712":"Florida Man Claims Drugs Hidden In Crotch Not His (The Smoking Gun)",
    "1812":"Florida Man Says Aliens Have Landed, Burns Down House Stocked With Flamethrowers And Ammo (Tampa Bay)",
    "1912":"Florida Man Says Scooter He Purchased Came With Meth & Other Drugs Inside (NY Post)",
    "2012":"Florida Man Maroons Himself On Lake Fountain Says He Wants To Be With The Swans, Blames ‘Too Much MDMA’ (KFOR)",
    "2112":"Florida Man Punches Mailboxes, Gets Tased 4 Times By Cops (Bradenton News)",
    "2212":"Florida Man Called Police Twice To Complain The Clams He Ordered Were ‘So Small’ (News Tribune)",
    "2312":"Florida Man Crashes Car Into Business While Trying To Time Travel (News 3LV)",
    "2412":"‘Time Traveling’ Florida Man Crashes Car Into Building (Florida Today)",
    "2512":"Florida Billboard Looks Hacked With Satanic Corgi, ‘Naughty’ Gorilla (WTSP)",
    "2612":"Florida Man Worried About Vampires Intentionally Burns Down His Home (WTXL)",
    "2712":"Florida Man Says He Punched ATM For Giving Too Much Cash (ABC Action News)",
    "2812":"Florida Man Shot Twice After Daring Brother To Shoot Him (Brevard Times)",
    "2912":"Florida Woman Robs Postal Truck With Fake Gun, Fled On Tricycle, Claimed She’s God (Rare US)",
    "3012":"Florida Man Rigs Door To Electrocute Pregnant Wife (Brevard Times)",
    "3112":"Florida Men Accused Of Stealing $500,000 Worth Of Tequila (WTSP)"
}

export default {
    async fetch(request) {
        const uri = new URL(request.url);
        const date = uri.searchParams.get("date") ?? "0000";
        if (date === "0000" || Math.random().toFixed(2) === Math.random().toFixed(2) || uri.pathname !== "/florida-man-blessed-you") {
            return Response.redirect("https://c.tenor.com/x8v1oNUOmg4AAAAd/tenor.gif", 301);
        }

        if (request.headers.get("User-Agent")) {
            return new Response(null, { status: 400 });
        }

        const isBirthday = (request.headers.get("Is-Birthday") ?? "false").toLowerCase();
        const developerMode = (request.headers.get("Developer-Mode") ?? "true").toLowerCase();
        const eotc = (request.headers.get("EOTC") ?? "true").toLowerCase();

        if (isBirthday === "false") {
            return new Response(null, { status: 200 });
        }
        if (isBirthday === "true") {
            return new Response(null, { status: 410 });
        }

        if (developerMode === "true") {
            return new Response(eotc === "true" ? "0" : "1", { status: 303 });
        }
        if (developerMode === "false") {
            return new Response(null, { status: 418 });
        }

        const whatHeDid = aDictContains366DaysThroughOutTheYearOnWhatAFloridaManAndWomanDidOnTheRequestedDay[date];
        const response = `{"A florida man did something on that day": "${whatHeDid != null ? "true" : "no idea"}","This is what he did": ${whatHeDid}}`;
        if (eotc === "true") {
            return new Response(response.slice(0, response.length / 2), { status: 303 });
        }
        if (eotc === "false") {
            return new Response(response, { status: 303 });
        }

        return new Response("im lazy man", { status: 501 });
    },
};
