from bs4 import BeautifulSoup
from datetime import datetime

the_html_to_parse = open("hoy.htm", "r", encoding="utf-8")

soup_I_can_eat = BeautifulSoup(the_html_to_parse.read(), "lxml")

the_html_to_parse.close()

the_big_chunk_that_im_extracting_out_of = soup_I_can_eat.find_all("p", class_="pw-post-body-paragraph md me gt mf b mg mh mi mj mk ml mm mn mo mp mq mr ms mt mu mv mw mx my mz na gn bj")

the_dict_that_I_want_to_put_in_the_date_as_key_and_a_string_contains_the_article_to_provide_it_to_user = {}

for content_that_I_want_to_extract_text_out_of in the_big_chunk_that_im_extracting_out_of:
    temp_variable_that_I_used_because_having_to_type_the_same_function_out_every_time_is_bad_for_the_environment_because_the_computer_uses_power_to_compute_it_so_I_made_this_to_make_it_uses_less_and_helping_my_bills_and_the_world = content_that_I_want_to_extract_text_out_of.find("strong", class_="mf gu")
    if temp_variable_that_I_used_because_having_to_type_the_same_function_out_every_time_is_bad_for_the_environment_because_the_computer_uses_power_to_compute_it_so_I_made_this_to_make_it_uses_less_and_helping_my_bills_and_the_world:
        convert_time_provided_in_the_extracted_text_from_the_html_so_I_could_later_format_it_as_key_for_each_day_through_out_the_year_of_what_a_florida_man_and_woman_did_on_that_day = datetime.strptime(temp_variable_that_I_used_because_having_to_type_the_same_function_out_every_time_is_bad_for_the_environment_because_the_computer_uses_power_to_compute_it_so_I_made_this_to_make_it_uses_less_and_helping_my_bills_and_the_world.text , '%B %d, %Y')
        the_dict_that_I_want_to_put_in_the_date_as_key_and_a_string_contains_the_article_to_provide_it_to_user.update({convert_time_provided_in_the_extracted_text_from_the_html_so_I_could_later_format_it_as_key_for_each_day_through_out_the_year_of_what_a_florida_man_and_woman_did_on_that_day.strftime("%d%m"): content_that_I_want_to_extract_text_out_of.text.replace(temp_variable_that_I_used_because_having_to_type_the_same_function_out_every_time_is_bad_for_the_environment_because_the_computer_uses_power_to_compute_it_so_I_made_this_to_make_it_uses_less_and_helping_my_bills_and_the_world.text, "")})

print(the_dict_that_I_want_to_put_in_the_date_as_key_and_a_string_contains_the_article_to_provide_it_to_user)